module.exports = {
    RESOURCE_CONTEXT_CREATE: 'RESOURCE_CONTEXT_CREATE',
    RESOURCE_CONTEXT_DESTROY: 'RESOURCE_CONTEXT_DESTROY',
    RESOURCE_CONTEXT_SELECT_RESOURCE: 'RESOURC_CONTEXT_SELECT_RESOURCE',
    RESOURCE_CONTEXT_SUBSCRIBE: 'RESOURC_CONTEXT_SUBSCRIBE'
};